languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Memesis"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo_memesis.jpg"
  description = "Il museo virtuale dei meme"

[params.author]
  name = "Memesis"
  image = "img/immagineprof.jpeg"
  headline = "Il museo dei meme"
  bio = "Il museo dei meme"
  links = [
    { youtube = "https://youtube.com/burufugu" },
    { facebook = "https://facebook.com/nunocoracao/blowfish" },
  ]