languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Memesis"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo_memesis.jpg"
  description = "I meme che hanno segnato la storia"

[params.author]
  name = "Memesis"
  image = "img/immagineprof.jpg"
  headline = "I meme che hanno segnato la storia"
  bio = "I meme che hanno segnato la storia"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]